{
 "title": "Home Power Consumption",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Energy Consumtion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Voltage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tuya_consumption_voltage", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Average Voltage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(tuya_consumption_voltage[$__range])",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "tuya_consumption_voltage", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Current Power",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tuya_consumption_power", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Average Power Consumption(OverTime)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(tuya_consumption_power[$__range])",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "description": "Power in watts",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "tuya_consumption_power", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Current Amp",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tuya_consumption_current", "legendFormat": "{{device_name}}" }
   ]
  },
  {
   "title": "Average Amp (OverTime)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(tuya_consumption_current[$__range])",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Amperage",
   "type": "timeseries",
   "description": "Power in watts",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "tuya_consumption_current", "legendFormat": "{{device_name}}" }
   ]
  },
  { "title": "Invertor Out", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Current Power",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tuya_consumption_power{location=\"Invertor Room\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Current Voltage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tuya_consumption_voltage{location=\"Invertor Room\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Current Amp",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tuya_consumption_current{location=\"Invertor Room\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "description": "Power in watts",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "tuya_consumption_power{location=\"Invertor Room\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "tuya_consumption_voltage{location=\"Invertor Room\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "tuya_consumption_current{location=\"Invertor Room\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  { "title": "Entertainment Unit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Current Power",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tuya_consumption_power{location=\"Living Room\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Current Voltage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tuya_consumption_voltage{location=\"Living Room\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Current Amp",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tuya_consumption_current{location=\"Living Room\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "description": "Power in watts",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "tuya_consumption_power{location=\"Living Room\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "tuya_consumption_voltage{location=\"Living Room\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "tuya_consumption_current{location=\"Living Room\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  }
 ]
}