    additionalPrometheusRules:
    - name: custom-recording-rules
      groups:
        - name: sum_node_by_job
          rules:
            - record: job:kube_node_labels:sum
              expr: sum(kube_node_labels) by (job)
        - name: sum_prometheus_config_reload_by_pod
          rules:
            - record: job:prometheus_config_last_reload_successful:sum
              expr: sum(prometheus_config_last_reload_successful) by (pod)
    - name: custom-alerting-rules
      groups:
        - name: prometheus-config
          rules:
            - alert: PrometheusConfigurationReload
              expr: prometheus_config_last_reload_successful > 0
              for: 1m
              labels:
                severity: error
              annotations:
                summary: "Prometheus configuration reload (instance {{ $labels.instance }})"
                description: "Prometheus configuration reload error\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
        - name: custom-node-exporter-alerting-rules
          rules:
            - alert: PhysicalComponentTooHot
              expr: node_hwmon_temp_celsius > 75
              for: 5m
              labels:
                severity: warning
              annotations:
                summary: "Physical component too hot (instance {{ $labels.instance }})"
                description: "Physical hardware component too hot\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
            - alert: NodeOvertemperatureAlarm
              expr: node_hwmon_temp_alarm == 1
              for: 5m
              labels:
                severity: critical
              annotations:
                summary: "Node overtemperature alarm (instance {{ $labels.instance }})"
                description: "Physical node temperature alarm triggered\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
        - name: custom-smartlife-alerting-rules
          rules:
            - alert: Voltage less than 220
              expr: sum(tuya_consumption_voltage) by (location) < 220
              for: 30s
              labels:
                severity: critical
              annotations:
                summary: "Voltage drop below 220 (instance {{ $labels.instance }})"
                description: "Voltage drop below 220. \n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"